### ISSUE TITLE
추가 도메인 설계

### ISSUE THREAD

**Issue by yunhoknight** [yunhoknight/fastcampus-project-board#60]
## Description

새로운 기능을 구현하기 위해 필요한 데이터 모델링 및 기존 도메인 변경부분 검토
## Todo
1. [ ] 기존 도메인 코드 분석
2. [ ] 대댓글 도메인 표현
3. [ ] 해시태그 도메인 표현
