### ISSUE TITLE
데이터베이스 접근 로직 테스트

### ISSUE THREAD

**Issue by yunhoknight** [yunhoknight/fastcampus-project-board#8]
## Description

도메인 설계 내용(#7)을 바탕으로 DB와 연동하기위한 방법을 구상하고, 세팅 및 테스트 작성
## Todo
1. [x] DB 기술 선택
2. [x] DB에 접근할 수 있는 상태로 환경 세팅하기
3. [x] 테스트 코드 작성

**Comment by yunhoknight** [comment]
MySQL로 DBMS 선택

* https://db-engines.com/en/ranking 참고
